// El catálogo de los cuadros del museo (#836): cinco fichas y sus cinco cartelas.
//
// POR QUÉ UN CATÁLOGO APARTE Y NO DOS ENTRADAS MÁS EN `museo-piezas.mjs`. No es
// orden: es que una estatua y un cuadro no se colocan igual. `CATALOGO_MUSEO`
// alimenta el reparto por PEDESTALES —fila, columna, cota de la coronilla— y
// meter ahí un cuadro le daría un pedestal en mitad de la sala. Un cuadro
// cuelga de un muro y su mirador mira al muro; son dos formas de colocar, y por
// eso son dos listas.
//
// LO QUE SÍ SE COMPARTE ES EL CONTRATO: estas fichas pasan por el MISMO
// `validarCatalogoPiezas` que las estatuas, con el mismo `naturaleza`
// obligatorio y la misma comprobación de que la `malla` referenciada existe de
// verdad. Lo único que cambia es contra qué registro se comprueba: allí son
// mallas de `data/mallas/`, aquí son composiciones de `museo-cuadro.mjs`. Dos
// validadores de licencia se desincronizan, y una licencia desincronizada no es
// un fallo de forma (#598).
//
// LAS DOS PRIMERAS SON `obra-propia`, Y ESA ES LA DECISIÓN QUE #836 TENÍA QUE
// TOMAR. La otra salida era colgar reproducciones de pintura real, y entonces
// ninguna de las cinco naturalezas servía: la fotografía de un óleo no es un
// escaneo, ni una fotogrametría, ni una reconstrucción. Habría hecho falta
// ampliar `NATURALEZAS`, traer los ficheros al árbol contra la regla de arte del
// módulo, y escribir procedencia real por cuadro. Pintarlos es lo que hace que
// no haya ninguna licencia ajena que gestionar — y de paso lo que permite decir
// en la cartela, sin rodeos, que lo que se mira lo generó una máquina.
//
// LAS TRES ÚLTIMAS SON OTRA COSA, Y POR ESO NO SON `obra-propia`. Son redibujos
// de tres paisajes de dominio público a partir de escaneos CC0, y ahí la
// decisión de arriba deja de valer: la composición no es nuestra y está
// identificada, así que llamarlas propias sería la única manera de que la sala
// enseñara la obra de alguien sin decirlo. De ahí el sexto valor de
// `NATURALEZAS`, `interpretacion`, y de ahí que su procedencia sea `cc` con la
// página que declara la licencia del escaneo. Lo que NO hay es fichero ajeno en
// el árbol: de la fuente sale la composición y nada más, así que estas fichas no
// llevan `sha256` ni comando de conversión — no hay nada que se haya copiado.
//
// LA CARTELA DE UN CUADRO GENERADO TIENE QUE DECIR QUE LO ES. Es la misma norma
// de la casa que obliga al León a decir que es una reconstrucción y a la
// Afrodita a decir que es un vaciado: la sala no enseña nada sin decir qué es
// exactamente lo que se está enseñando. Una prueba lo comprueba en los dos
// idiomas, igual que con las estatuas.
//
// Puro: datos y nada más.

import { COMPOSICIONES } from "./museo-cuadro.mjs";

/** Los IDs de composición que existen. El registro contra el que valida el
 *  catálogo: una ficha que apunte a un dibujo que no está no llega a la sala. */
export const MALLAS_CUADROS = Object.freeze(Object.keys(COMPOSICIONES));

/** La procedencia de las dos generadas, y es la más corta posible: no hay
 *  fuente externa. `original` es el `kind` que `procedencia-catalogo.mjs`
 *  reserva justo para esto, y por eso no lleva `source_url`: no hay ninguna
 *  página que consultar, el dibujo está en el árbol. */
const PROCEDENCIA_PROPIA = Object.freeze({
  kind: "original",
  source: "Espaciokoop Lagunak: pixelart generado por scripts/museo-cuadro.mjs",
  license: "GPL-2.0-or-later, como el resto del módulo",
});

export const CATALOGO_CUADROS = Object.freeze({
  formato: "espaciokoop-piezas",
  version: 1,
  piezas: Object.freeze([
    Object.freeze({
      id: "campo-partido",
      malla: "campo-partido",
      naturaleza: "obra-propia",
      nombre: Object.freeze({
        es: "Campo partido",
        en: "Divided field",
      }),
      cartela: Object.freeze({
        es: "No es una pintura: es una composición GENERADA por el propio"
          + " módulo, píxel a píxel, a dos centímetros y medio por píxel. No"
          + " reproduce ningún cuadro que exista ni pretende que lo parezca. Dos"
          + " masas de tierra que no se tocan y una línea de luz que no llega a"
          + " los bordes — si cruzara el lienzo entero sería un horizonte, y un"
          + " horizonte ya sería un sitio.",
        en: "This is not a painting: it is a composition GENERATED by the module"
          + " itself, pixel by pixel, at two and a half centimetres per pixel."
          + " It reproduces no existing work and does not pretend to. Two earth"
          + " masses that never meet and a line of light that stops short of the"
          + " edges — crossing the whole canvas it would be a horizon, and a"
          + " horizon would already be a place.",
      }),
      provenance: PROCEDENCIA_PROPIA,
    }),
    Object.freeze({
      id: "contratiempo-de-verdin",
      malla: "contratiempo-de-verdin",
      naturaleza: "obra-propia",
      nombre: Object.freeze({
        es: "Contratiempo de verdín",
        en: "Verdigris offbeat",
      }),
      cartela: Object.freeze({
        es: "También GENERADA por el módulo, y a propósito distinta de la de"
          + " enfrente: aquella es masa contra masa y esta es ritmo. Cinco"
          + " manchas que no se apoyan en la misma línea, de anchos y alturas"
          + " sin orden, dos de ellas cortadas por el borde — el dibujo sigue"
          + " fuera del cuadro. Un solo trazo de hueso las cruza en horizontal.",
        en: "Also GENERATED by the module, and deliberately unlike the one"
          + " across the room: that one is mass against mass, this one is"
          + " rhythm. Five patches that share no baseline, of unordered widths"
          + " and heights, two of them cut by the edge — the drawing carries on"
          + " outside the canvas. A single bone-white stroke crosses them.",
      }),
      provenance: PROCEDENCIA_PROPIA,
    }),
    Object.freeze({
      id: "frente-al-mar",
      malla: "frente-al-mar",
      naturaleza: "interpretacion",
      nombre: Object.freeze({
        es: "Frente al mar (según Hokusai)",
        en: "Facing the sea (after Hokusai)",
      }),
      cartela: Object.freeze({
        es: "REDIBUJO, no una reproducción: la gran ola de Kanagawa de Katsushika"
          + " Hokusai (c. 1830), vuelta a componer píxel a píxel por este módulo a"
          + " partir de un escaneo de dominio público. Ni un punto del original"
          + " está aquí; lo que se conserva es la desproporción, que es de lo que"
          + " trata el grabado: el agua ocupa media tabla y la montaña son seis"
          + " filas al fondo.",
        en: "A REDRAWING, not a reproduction: Katsushika Hokusai's great wave off"
          + " Kanagawa (c. 1830), recomposed pixel by pixel by this module from a"
          + " public-domain scan. Not one dot of the original is here; what"
          + " survives is the disproportion the print is about — the water takes"
          + " half the panel and the mountain is six rows at the back.",
      }),
      provenance: Object.freeze({
        kind: "cc",
        source: "Escaneo de dominio público del grabado de Katsushika Hokusai, vía Wikimedia Commons",
        license: "Dominio público (obra de c. 1830); el escaneo, sin derechos reclamados",
        source_url:
          "https://commons.wikimedia.org/wiki/File:Tsunami_by_hokusai_19th_century.jpg",
      }),
    }),
    Object.freeze({
      id: "viento-del-sur",
      malla: "viento-del-sur",
      naturaleza: "interpretacion",
      nombre: Object.freeze({
        es: "Viento del sur (según Hokusai)",
        en: "South wind (after Hokusai)",
      }),
      cartela: Object.freeze({
        es: "REDIBUJO del «Viento del sur, cielo despejado» de Katsushika Hokusai"
          + " (c. 1830), de la misma serie que la ola de enfrente. Se eligió"
          + " porque a esta resolución no pierde nada: un cono rojo, la nieve"
          + " arriba, el bosque abajo y tres nubes en banda. El original tampoco"
          + " tenía mucho más.",
        en: "A REDRAWING of Katsushika Hokusai's «South Wind, Clear Sky»"
          + " (c. 1830), from the same series as the wave across the room. It was"
          + " chosen because it loses nothing at this resolution: a red cone, snow"
          + " on top, forest below and three banded clouds. The original had"
          + " little more.",
      }),
      provenance: Object.freeze({
        kind: "cc",
        source: "Escaneo de dominio público del grabado de Katsushika Hokusai, vía Wikimedia Commons",
        license: "Dominio público (obra de c. 1830); el escaneo, sin derechos reclamados",
        source_url:
          "https://commons.wikimedia.org/wiki/File:Red_Fuji_southern_wind_clear_morning.jpg",
      }),
    }),
    Object.freeze({
      id: "sobre-la-niebla",
      malla: "sobre-la-niebla",
      naturaleza: "interpretacion",
      nombre: Object.freeze({
        es: "Sobre la niebla (según Friedrich)",
        en: "Above the fog (after Friedrich)",
      }),
      cartela: Object.freeze({
        es: "REDIBUJO del «Caminante sobre el mar de nubes» de Caspar David"
          + " Friedrich (c. 1818), a partir de un escaneo de dominio público. La"
          + " figura son ocho píxeles de espaldas, y así se queda: a contraluz no"
          + " hay cara que enseñar, y el cuadro nunca fue el retrato de nadie.",
        en: "A REDRAWING of Caspar David Friedrich's «Wanderer above the Sea of"
          + " Fog» (c. 1818), from a public-domain scan. The figure is eight"
          + " pixels seen from behind, and stays that way: against the light there"
          + " is no face to show, and the painting was never anyone's portrait.",
      }),
      provenance: Object.freeze({
        kind: "cc",
        source:
          "Escaneo de dominio público del óleo de Caspar David Friedrich, vía Wikimedia Commons",
        license: "Dominio público (obra de c. 1818); el escaneo, sin derechos reclamados",
        source_url:
          "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
      }),
    }),
  ]),
});
